### ISSUE TITLE
Uncaught TypeError: img.toPng is not a function

### ISSUE THREAD

**Issue by cm3** [bigyuki/markdown-image-helper#14]
[Enter steps to reproduce:]

1. Copy img to the clipboard, press ctrl+V in the editor, then the error arose.

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Windows 10
**Thrown From**: [markdown-image-helper](https://github.com/bigyuki/markdown-image-helper) package 1.0.4

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At C:\Users\User\.atom\packages\markdown-image-helper\lib\main.coffee:24

TypeError: img.toPng is not a function
    at /packages/markdown-image-helper/lib/main.coffee:24:21
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  4x -0:08.4.0 core:page-down (input.hidden-input)
     -0:07.5.0 core:move-up (input.hidden-input)
     -0:07.3.0 core:move-left (input.hidden-input)
  2x -0:07.1.0 core:move-down (input.hidden-input)
  2x -0:06.4.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-dedupe-open-files 0.1.0 
atom-monokai-dark 0.4.0 
convert-to-utf8 0.2.4 
date 2.1.0 
language-latex 1.1.1 
markdown-image-helper 1.0.4 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
wordcount 2.10.4 
```

**Comment by cm3** [comment]
I found the solution, `toPng` is now `toPNG`. [Electron has been upgraded to version 2.0 in atom 1.28.0](https://github.com/atom/atom/releases) and [The \(deprecated\) NativeImage\.toPng was removed in 2\.0\.0](https://github.com/electron/electron/issues/13169).

**Comment by llogs** [comment]
I have also in trouble on mac OS with same issue above. How can i fix it?
